name: E2E (main)

on:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: Update snapshots
        run: npx playwright test --update-snapshots
        env:
          CI: true
      - name: E2E
        run: npm run test:e2e
        env:
          CI: true
