name: Review

on:
  pull_request:
    branches: [main]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Prettier
        run: npx prettier --ignore-unknown --write .
      - name: Linting
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

  # e2e:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npx playwright install --with-deps chromium
  #     - name: E2E
  #       run: npm run test:e2e
  #       env:
  #         CI: true

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npx next start &
      - run: npx wait-on http://localhost:3000
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress http://localhost:3000
        continue-on-error: true
